### ISSUE TITLE
Problem with training on CPU (apex)

### ISSUE THREAD

**Issue by mkareshk** [benbogin/spider-schema-gnn#2]
I tried to train the model on a CPU-based system, but I got the following error:

`2019-06-03 10:10:17,299 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved 
with apex installed from https://www.github.com/nvidia/apex .
usage: allennlp
allennlp: error: unrecognized arguments:  
./train.sh: line 5: --include-package: command not found `

I cannot install apex since I don't have CUDA on my system. Is it possible to train the model on a CPU, or having a GPU is part of the repository requirement?

Thank for the help!

**Comment by benbogin** [comment]
The model should work on CPU. You will need to make sure you have the correct pytorch version first, and in the config file, you'll have to change the "cuda_device" value (under "trainer") to -1, to indicate that you don't use the GPU.

The apex warning is just a warning - you can ignore it.

The actual error seems to be a command syntax error - the error `--include-package: command not found` probably indicates that the command was executed as multiple lines, instead of a single one. Can you try fixing the command or post here what you ran?

**Comment by mkareshk** [comment]
Thanks! The problem is solved.
