### ISSUE TITLE
Inconsistent behavior on reading values in train/test

### ISSUE THREAD

**Issue by SivilTaram** [benbogin/spider-schema-gnn#7]
Hi Bogin, thanks for open-sourcing the excellent code! I have learned a lot from your code :) However, I have one strange question about the entity `string` and want to ask for your help.

From my personal viewpoint, the `string` entity is tied with database values, right? (Refer to function `read_dataset_values` and `get_entities_from_question` ). However, as far as I know, the Spider dataset does not allow to read values in database  in test. So I guess there should be a gap between train and test: given a  utterance, in training, we could somehow know whether one word is corresponding to the database values; But in test, we cannot even get the `string` entity. 

But from the small difference gap between train and test performance in the leaderboard, I do not know whether my guess is correct. So I want to know, will you OBTAIN the database values in test? If no, how to handle the above inconsistent problem? And what it the insight or motivation to read the dataset values? Thanks for your patience, looking forward to your response!

**Comment by benbogin** [comment]
Hi! I'm glad you've find the code useful.

It is allowed to use the values at test time since the database schema and values are available to you (although of course they were never seen at training time).

The intuition for that is that if you ask something like "List the clubs having "Davis Steven" as a member", and you know "Davis Steven" is a value under the column 'name', it is more likely that you will want to use the column 'name'.

**Comment by SivilTaram** [comment]
Many thanks for the quick response! Now I understand the motivation behind it. Thanks again!
